// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AreaBox_V0._1.Models.Dto;


public class CategoriesDto
{
    public int CategoryId { get; set; }

    public string CategoryName { get; set; }

    public virtual ICollection<MediaPostsDto> MediaPosts { get; set; } = new List<MediaPostsDto>();

    public virtual ICollection<QuestionPostsDto> QuestionPosts { get; set; } = new List<QuestionPostsDto>();
}