// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable


namespace AreaBox_V0._1.Models.Dto;


public class CitiesDto
{
    public int CitryId { get; set; }

    public string CityName { get; set; }

    public int CountryId { get; set; }

    public virtual CountriesDto Country { get; set; }

    public virtual ICollection<MediaPostsDto> MediaPosts { get; set; } = new List<MediaPostsDto>();

    public virtual ICollection<QuestionPostsDto> QuestionPosts { get; set; } = new List<QuestionPostsDto>();
}