// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable


namespace AreaBox_V0._1.Models.Dto;

public class CountriesDto
{
    public int CountryId { get; set; }

    public string CountryName { get; set; }

    public virtual ICollection<CitiesDto> Cities { get; set; } = new List<CitiesDto>();
}