// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable

namespace AreaBox_V0._1.Data.Model;

public partial class Cities
{
    public int CitryId { get; set; }

    public string CityName { get; set; }

    public int CountryId { get; set; }

    public virtual Countries Country { get; set; }

    public virtual ICollection<MediaPosts> MediaPosts { get; set; } = new List<MediaPosts>();

    public virtual ICollection<QuestionPosts> QuestionPosts { get; set; } = new List<QuestionPosts>();
}