// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace AreaBox_V0._1.Models;

public partial class AreaBoxDbContext : DbContext
{
    public AreaBoxDbContext(DbContextOptions<AreaBoxDbContext> options)
        : base(options)
    {
    }

    public virtual DbSet<AspNetRoleClaims> AspNetRoleClaims { get; set; }

    public virtual DbSet<AspNetRoles> AspNetRoles { get; set; }

    public virtual DbSet<AspNetUserClaims> AspNetUserClaims { get; set; }

    public virtual DbSet<AspNetUserLogins> AspNetUserLogins { get; set; }

    public virtual DbSet<AspNetUserTokens> AspNetUserTokens { get; set; }

    public virtual DbSet<AspNetUsers> AspNetUsers { get; set; }

    public virtual DbSet<Categories> Categories { get; set; }

    public virtual DbSet<Cities> Cities { get; set; }

    public virtual DbSet<Countries> Countries { get; set; }

    public virtual DbSet<MediaPostComments> MediaPostComments { get; set; }

    public virtual DbSet<MediaPostLikes> MediaPostLikes { get; set; }

    public virtual DbSet<MediaPosts> MediaPosts { get; set; }

    public virtual DbSet<MediaPostsReports> MediaPostsReports { get; set; }

    public virtual DbSet<QuestionPostComments> QuestionPostComments { get; set; }

    public virtual DbSet<QuestionPosts> QuestionPosts { get; set; }

    public virtual DbSet<QuestionPostsReports> QuestionPostsReports { get; set; }

    public virtual DbSet<ReportTypes> ReportTypes { get; set; }

    public virtual DbSet<TechnicalReports> TechnicalReports { get; set; }

    public virtual DbSet<UsersMediaPostComments> UsersMediaPostComments { get; set; }

    public virtual DbSet<UsersQusetionPostComments> UsersQusetionPostComments { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<AspNetRoleClaims>(entity =>
        {
            entity.HasIndex(e => e.RoleId, "IX_AspNetRoleClaims_RoleId");

            entity.Property(e => e.RoleId).IsRequired();

            entity.HasOne(d => d.Role).WithMany(p => p.AspNetRoleClaims).HasForeignKey(d => d.RoleId);
        });

        modelBuilder.Entity<AspNetRoles>(entity =>
        {
            entity.HasIndex(e => e.NormalizedName, "RoleNameIndex")
                .IsUnique()
                .HasFilter("([NormalizedName] IS NOT NULL)");

            entity.Property(e => e.Name).HasMaxLength(256);
            entity.Property(e => e.NormalizedName).HasMaxLength(256);
        });

        modelBuilder.Entity<AspNetUserClaims>(entity =>
        {
            entity.HasIndex(e => e.UserId, "IX_AspNetUserClaims_UserId");

            entity.Property(e => e.UserId).IsRequired();

            entity.HasOne(d => d.User).WithMany(p => p.AspNetUserClaims).HasForeignKey(d => d.UserId);
        });

        modelBuilder.Entity<AspNetUserLogins>(entity =>
        {
            entity.HasKey(e => new { e.LoginProvider, e.ProviderKey });

            entity.HasIndex(e => e.UserId, "IX_AspNetUserLogins_UserId");

            entity.Property(e => e.UserId).IsRequired();

            entity.HasOne(d => d.User).WithMany(p => p.AspNetUserLogins).HasForeignKey(d => d.UserId);
        });

        modelBuilder.Entity<AspNetUserTokens>(entity =>
        {
            entity.HasKey(e => new { e.UserId, e.LoginProvider, e.Name });

            entity.HasOne(d => d.User).WithMany(p => p.AspNetUserTokens).HasForeignKey(d => d.UserId);
        });

        modelBuilder.Entity<AspNetUsers>(entity =>
        {
            entity.HasIndex(e => e.NormalizedEmail, "EmailIndex");

            entity.HasIndex(e => e.NormalizedUserName, "UserNameIndex")
                .IsUnique()
                .HasFilter("([NormalizedUserName] IS NOT NULL)");

            entity.Property(e => e.Email).HasMaxLength(256);
            entity.Property(e => e.NormalizedEmail).HasMaxLength(256);
            entity.Property(e => e.NormalizedUserName).HasMaxLength(256);
            entity.Property(e => e.UserName).HasMaxLength(256);

            entity.HasMany(d => d.Role).WithMany(p => p.User)
                .UsingEntity<Dictionary<string, object>>(
                    "AspNetUserRoles",
                    r => r.HasOne<AspNetRoles>().WithMany().HasForeignKey("RoleId"),
                    l => l.HasOne<AspNetUsers>().WithMany().HasForeignKey("UserId"),
                    j =>
                    {
                        j.HasKey("UserId", "RoleId");
                        j.HasIndex(new[] { "RoleId" }, "IX_AspNetUserRoles_RoleId");
                    });
        });

        modelBuilder.Entity<Categories>(entity =>
        {
            entity.HasKey(e => e.CategoryId);

            entity.Property(e => e.CategoryId).HasColumnName("CategoryID");
            entity.Property(e => e.CategoryName)
                .IsRequired()
                .HasMaxLength(100);
        });

        modelBuilder.Entity<Cities>(entity =>
        {
            entity.HasKey(e => e.CitryId);

            entity.Property(e => e.CitryId).HasColumnName("CitryID");
            entity.Property(e => e.CityName)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.CountryId).HasColumnName("CountryID");

            entity.HasOne(d => d.Country).WithMany(p => p.Cities)
                .HasForeignKey(d => d.CountryId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Cities_Countries");
        });

        modelBuilder.Entity<Countries>(entity =>
        {
            entity.HasKey(e => e.CountryId);

            entity.Property(e => e.CountryId).HasColumnName("CountryID");
            entity.Property(e => e.CountryName)
                .IsRequired()
                .HasMaxLength(100);
        });

        modelBuilder.Entity<MediaPostComments>(entity =>
        {
            entity.HasKey(e => e.MpcommentId);

            entity.Property(e => e.MpcommentId).HasColumnName("MPCommentID");
            entity.Property(e => e.MpcommentContent)
                .IsRequired()
                .HasColumnName("MPCommentContent");
            entity.Property(e => e.MpcommnetDate)
                .HasColumnType("datetime")
                .HasColumnName("MPCommnetDate");
            entity.Property(e => e.MpostId)
                .IsRequired()
                .HasMaxLength(450)
                .HasColumnName("MPostID");

            entity.HasOne(d => d.Mpost).WithMany(p => p.MediaPostComments)
                .HasForeignKey(d => d.MpostId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_MediaPostComments_MediaPosts");
        });

        modelBuilder.Entity<MediaPostLikes>(entity =>
        {
            entity.HasNoKey();

            entity.Property(e => e.MpostId)
                .IsRequired()
                .HasMaxLength(450)
                .HasColumnName("MPostID");
            entity.Property(e => e.UserId)
                .IsRequired()
                .HasMaxLength(450)
                .HasColumnName("UserID");

            entity.HasOne(d => d.Mpost).WithMany()
                .HasForeignKey(d => d.MpostId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_MediaPostLikes_MediaPosts");

            entity.HasOne(d => d.User).WithMany()
                .HasForeignKey(d => d.UserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_MediaPostLikes_AspNetUsers");
        });

        modelBuilder.Entity<MediaPosts>(entity =>
        {
            entity.HasKey(e => e.MpostId);

            entity.Property(e => e.MpostId).HasColumnName("MPostID");
            entity.Property(e => e.MpcategoryId).HasColumnName("MPCategoryID");
            entity.Property(e => e.MpcityId).HasColumnName("MPCityID");
            entity.Property(e => e.Mpdate)
                .HasColumnType("datetime")
                .HasColumnName("MPDate");
            entity.Property(e => e.Mpimage)
                .IsRequired()
                .HasColumnName("MPImage");
            entity.Property(e => e.MplongDescription)
                .IsRequired()
                .HasMaxLength(450)
                .HasColumnName("MPLongDescription");
            entity.Property(e => e.MpshortDescription)
                .IsRequired()
                .HasMaxLength(150)
                .HasColumnName("MPShortDescription");
            entity.Property(e => e.Mpstate).HasColumnName("MPState");
            entity.Property(e => e.MpuserId)
                .IsRequired()
                .HasMaxLength(450)
                .HasColumnName("MPUserID");

            entity.HasOne(d => d.Mpcategory).WithMany(p => p.MediaPosts)
                .HasForeignKey(d => d.MpcategoryId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_MediaPosts_Categories");

            entity.HasOne(d => d.Mpcity).WithMany(p => p.MediaPosts)
                .HasForeignKey(d => d.MpcityId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_MediaPosts_Cities");

            entity.HasOne(d => d.Mpuser).WithMany(p => p.MediaPosts)
                .HasForeignKey(d => d.MpuserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_MediaPosts_AspNetUsers");
        });

        modelBuilder.Entity<MediaPostsReports>(entity =>
        {
            entity.HasNoKey();

            entity.Property(e => e.MpostId)
                .IsRequired()
                .HasMaxLength(450)
                .HasColumnName("MPostID");
            entity.Property(e => e.ReportTypeId).HasColumnName("ReportTypeID");

            entity.HasOne(d => d.Mpost).WithMany()
                .HasForeignKey(d => d.MpostId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_MediaPostsReports_MediaPosts");

            entity.HasOne(d => d.ReportType).WithMany()
                .HasForeignKey(d => d.ReportTypeId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_MediaPostsReports_ReportTypes");
        });

        modelBuilder.Entity<QuestionPostComments>(entity =>
        {
            entity.HasKey(e => e.QpcommentId);

            entity.Property(e => e.QpcommentId).HasColumnName("QPCommentID");
            entity.Property(e => e.QpcommentContent)
                .IsRequired()
                .HasColumnName("QPCommentContent");
            entity.Property(e => e.QpcommentDate)
                .HasColumnType("datetime")
                .HasColumnName("QPCommentDate");
            entity.Property(e => e.QpostId)
                .IsRequired()
                .HasMaxLength(450)
                .HasColumnName("QPostID");

            entity.HasOne(d => d.Qpost).WithMany(p => p.QuestionPostComments)
                .HasForeignKey(d => d.QpostId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_QuestionPostComments_QuestionPosts");
        });

        modelBuilder.Entity<QuestionPosts>(entity =>
        {
            entity.HasKey(e => e.QpostId);

            entity.Property(e => e.QpostId).HasColumnName("QPostID");
            entity.Property(e => e.QpcategoryId).HasColumnName("QPCategoryID");
            entity.Property(e => e.QpcityId).HasColumnName("QPCityID");
            entity.Property(e => e.Qpdate)
                .HasColumnType("datetime")
                .HasColumnName("QPDate");
            entity.Property(e => e.Qpdescription)
                .IsRequired()
                .HasColumnName("QPDescription");
            entity.Property(e => e.Qpstate).HasColumnName("QPState");
            entity.Property(e => e.Qptitle)
                .IsRequired()
                .HasMaxLength(100)
                .HasColumnName("QPTitle");
            entity.Property(e => e.QpuserId)
                .IsRequired()
                .HasMaxLength(450)
                .HasColumnName("QPUserID");

            entity.HasOne(d => d.Qpcategory).WithMany(p => p.QuestionPosts)
                .HasForeignKey(d => d.QpcategoryId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_QuestionPosts_Categories");

            entity.HasOne(d => d.Qpcity).WithMany(p => p.QuestionPosts)
                .HasForeignKey(d => d.QpcityId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_QuestionPosts_Cities");

            entity.HasOne(d => d.Qpuser).WithMany(p => p.QuestionPosts)
                .HasForeignKey(d => d.QpuserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_QuestionPosts_AspNetUsers");
        });

        modelBuilder.Entity<QuestionPostsReports>(entity =>
        {
            entity.HasNoKey();

            entity.Property(e => e.QpostId)
                .IsRequired()
                .HasMaxLength(450)
                .HasColumnName("QPostID");
            entity.Property(e => e.ReportTypeId).HasColumnName("ReportTypeID");

            entity.HasOne(d => d.Qpost).WithMany()
                .HasForeignKey(d => d.QpostId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_QuestionPostsReports_QuestionPosts");

            entity.HasOne(d => d.ReportType).WithMany()
                .HasForeignKey(d => d.ReportTypeId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_QuestionPostsReports_ReportTypes");
        });

        modelBuilder.Entity<ReportTypes>(entity =>
        {
            entity.HasKey(e => e.ReportTypeId);

            entity.Property(e => e.ReportTypeId).HasColumnName("ReportTypeID");
            entity.Property(e => e.Type)
                .IsRequired()
                .HasMaxLength(150);
        });

        modelBuilder.Entity<TechnicalReports>(entity =>
        {
            entity.HasKey(e => e.TechnicalReportId);

            entity.Property(e => e.TechnicalReportId).HasColumnName("TechnicalReportID");
            entity.Property(e => e.Details).IsRequired();
            entity.Property(e => e.Type)
                .IsRequired()
                .HasMaxLength(150);
            entity.Property(e => e.UserEmail).HasMaxLength(450);
            entity.Property(e => e.UserId)
                .IsRequired()
                .HasMaxLength(450)
                .HasColumnName("UserID");

            entity.HasOne(d => d.User).WithMany(p => p.TechnicalReports)
                .HasForeignKey(d => d.UserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_TechnicalReports_AspNetUsers");
        });

        modelBuilder.Entity<UsersMediaPostComments>(entity =>
        {
            entity.HasNoKey();

            entity.Property(e => e.MpcommentId)
                .IsRequired()
                .HasMaxLength(450)
                .HasColumnName("MPCommentID");
            entity.Property(e => e.UserId)
                .IsRequired()
                .HasMaxLength(450)
                .HasColumnName("UserID");

            entity.HasOne(d => d.Mpcomment).WithMany()
                .HasForeignKey(d => d.MpcommentId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_UsersMediaPostComments_MediaPostComments");

            entity.HasOne(d => d.User).WithMany()
                .HasForeignKey(d => d.UserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_UsersMediaPostComments_AspNetUsers");
        });

        modelBuilder.Entity<UsersQusetionPostComments>(entity =>
        {
            entity.HasNoKey();

            entity.Property(e => e.QpcommentId)
                .IsRequired()
                .HasMaxLength(450)
                .HasColumnName("QPCommentID");
            entity.Property(e => e.UserId)
                .IsRequired()
                .HasMaxLength(450)
                .HasColumnName("UserID");

            entity.HasOne(d => d.Qpcomment).WithMany()
                .HasForeignKey(d => d.QpcommentId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_UsersQusetionPostComments_QuestionPostComments");

            entity.HasOne(d => d.User).WithMany()
                .HasForeignKey(d => d.UserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_UsersQusetionPostComments_AspNetUsers");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}