// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AreaBox_V0._1.Models;

public partial class Categories
{
    public int CategoryId { get; set; }

    public string CategoryName { get; set; }

    public virtual ICollection<MediaPosts> MediaPosts { get; set; } = new List<MediaPosts>();

    public virtual ICollection<QuestionPosts> QuestionPosts { get; set; } = new List<QuestionPosts>();
}