// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AreaBox_V0._1.Models;

public partial class Countries
{
    public int CountryId { get; set; }

    public string CountryName { get; set; }

    public virtual ICollection<Cities> Cities { get; set; } = new List<Cities>();
}