// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AreaBox_V0._1.Models;

public partial class MediaPostComments
{
    public string MpcommentId { get; set; }

    public string MpostId { get; set; }

    public DateTime MpcommnetDate { get; set; }

    public string MpcommentContent { get; set; }

    public virtual MediaPosts Mpost { get; set; }
}