// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AreaBox_V0._1.Models;

public partial class QuestionPostComments
{
    public string QpcommentId { get; set; }

    public string QpostId { get; set; }

    public DateTime QpcommentDate { get; set; }

    public string QpcommentContent { get; set; }

    public virtual QuestionPosts Qpost { get; set; }
}