// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AreaBox_V0._1.Models;

public partial class QuestionPostsReports
{
    public int ReportTypeId { get; set; }

    public string QpostId { get; set; }

    public virtual QuestionPosts Qpost { get; set; }

    public virtual ReportTypes ReportType { get; set; }
}