// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AreaBox_V0._1.Models;

public partial class QuestionPosts
{
    public string QpostId { get; set; }

    public int QpcategoryId { get; set; }

    public int QpcityId { get; set; }

    public DateTime Qpdate { get; set; }

    public string QpuserId { get; set; }

    public string Qptitle { get; set; }

    public string Qpdescription { get; set; }

    public bool Qpstate { get; set; }

    public virtual Categories Qpcategory { get; set; }

    public virtual Cities Qpcity { get; set; }

    public virtual AspNetUsers Qpuser { get; set; }

    public virtual ICollection<QuestionPostComments> QuestionPostComments { get; set; } = new List<QuestionPostComments>();
}